#!/bin/sh
#
# @name HolyBro X500 v2 Research Drone (ROS2/MAVROS)
# @type Quadrotor x
# @class Copter
#
# @maintainer Quinn Simmonds

. ${R}etc/init.d/rc.mc_defaults

# Default Parameters for Gazebo
PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=indoor_env0}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500_research}

# Vehicle geometry
param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.174
param set-default CA_ROTOR0_PY -0.174
param set-default CA_ROTOR1_PX -0.174
param set-default CA_ROTOR1_PY 0.174
param set-default CA_ROTOR2_PX 0.174
param set-default CA_ROTOR2_PY 0.174
param set-default CA_ROTOR3_PX -0.174
param set-default CA_ROTOR3_PY -0.174

param set-default CA_ROTOR0_CT 1
param set-default CA_ROTOR1_CT 1
param set-default CA_ROTOR2_CT -1
param set-default CA_ROTOR3_CT -1

# Motor outputs
param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104

# SITL-specific: Disable hardware interfaces
param set-default SIM_GZ_EN 1
param set-default SENS_EN_THERMAL 0
